# Generated by Django 3.1.1 on 2020-09-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_appliances'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appliances',
            new_name='Appliance',
        ),
    ]
