# Generated by Django 3.1.1 on 2020-09-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200920_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='Computers_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Decoders_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='ElectricBlanket_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Fridges_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Heaters_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Kettles_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Lights_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Microwaves_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Modems_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Phones_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Printers_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='SoundSystems_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Stoves_num',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='TVs_num',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
