# Generated by Django 3.1.1 on 2020-09-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200921_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appliance',
            new_name='Appliance_list',
        ),
    ]
