# Generated by Django 3.1.1 on 2020-09-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200921_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance_list',
            old_name='ElectricBlanket_num',
            new_name='ElectricBlankets_num',
        ),
    ]
