# Generated by Django 3.1.1 on 2020-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200922_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance_list',
            name='Computers_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Decoders_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='ElectricBlankets_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Fridges_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Heaters_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Kettles_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Lights_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Microwaves_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Modems_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Phones_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Printers_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='SoundSystems_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='Stoves_num',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='appliance_list',
            name='TVs_num',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
